//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class attack
{
	int attackvalue;
	bool ison;
	int power;
	int[] attackrange;
	skill[] s;
	public attack ()
	{
		attackvalue = 0;
		ison = false;
		power = 10;
		attackrange = new int[6];
		for (int i=0; i<6; i++) {
			attackrange[i]=0;
				}
		s = new skill[4];
		for(int i=0; i<4; i++) {
			s[i]=new skill();
		}
	}
	public void setPower (int p){
		power = p;
	}
	public void setAttackvalue (int v){
		attackvalue = v;
	}
	public void setAttackrange (int n,int hit){
		attackrange[n]=hit;
	}
	public void setskill (skill sk,int i){
		s[i] = sk;
	}
	public int getPower(){
		return power;
	}
	public int getAttackvalue(){
		return attackvalue;
	}
	public int[] getattackrange(){
		return attackrange;
	}
	public skill[] getSkill(){
		return s;
	}
	public void changeOnOff(){
		if (ison)
			ison = false;
		else
			ison = true;
		}
	public bool isOn(){
		return ison;
	}
	public string[] tostring(){
		string[] result = new string[17];
		result [0] = ison.ToString();
		result [1] = attackvalue.ToString ();
		result [2] = power.ToString ();
		for (int i=0; i<6; i++) {
			result[3+i]=attackrange[i].ToString();
		}
		for(int i=0; i<4; i++) {
			string[] temp= s[i].tostring();
			result[9+2*i]=temp[0];
			result[10+2*i]=temp[1];
		}
		return result;
	}
	public void assignstring(string[] str){
		ison = bool.Parse(str [0]);
		attackvalue = int.Parse (str [1]);
		power = int.Parse (str [2]);
		for (int i=0; i<6; i++) {
			attackrange[i] = int.Parse (str [3+i]);
		}
		for(int i=0; i<4; i++) {
			string[] temp= new string[2];
			temp[0]=str[9+2*i];
			temp[1]=str[10+2*i];
			s[i].assignstring(temp);
		}
	}
	public string getType(){
		if (ison) {
						for (int i=0; i<4; i++) {
								if (s [i].getLevel () > 5) {
										return s [i].getName ();
								}
						}
						if (attackrange [0] + attackrange [1] + attackrange [2] + attackrange [3] + attackrange [4] + attackrange [5] > 5) {
								return "attackvalue";
						}
						return "power";
				} else
						return "null";
	}
}

