//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class attack
{
	double power;
	int hitnumber;
	bool[] attackrange;
	skill s1;
	skill s2;
	public attack ()
	{
		power = 1.0;
		hitnumber = 1;
		attackrange = new bool[9];
		for (int i=0; i<9; i++) {
			attackrange[i]=false;
				}
		s1 = new skill ("0", 1);
		s2 = new skill ("0", 1);
	}
	public void setPower (double p){
		power = p;
	}
	public void sethitnumber (int n){
		hitnumber = n;
	}
	public void changeattackrange (int n){
		if (attackrange[n]){
			attackrange[n]=false;
		}
		else {
			attackrange[n]=true;
		}
	}
	public void setskill1 (skill s){
		s1 = s;
	}
	public void setskill2 (skill s){
		s2 = s;
	}
	public double getPower(){
		return power;
	}
	public int getHitnumber(){
		return hitnumber;
	}
	public bool[] getattackrange(){
		return attackrange;
	}
	public skill getSkill1(){
		return s1;
	}
	public skill getSkill2(){
		return s2;
	}
}

