//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18052
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class attack
{
	int power;
	int[] attackrange;
	skill[] s;
	public attack ()
	{
		power = 10;
		attackrange = new int[6];
		for (int i=0; i<6; i++) {
			attackrange[i]=0;
				}
		s = new skill[4];
		for(int i=0; i<4; i++) {
			s[i]=new skill();
		}
	}
	public void setPower (int p){
		power = p;
	}
	public void setAttackrange (int n,int hit){
		attackrange[n]=hit;
	}
	public void setskill (skill sk,int i){
		s[i] = sk;
	}
	public int getPower(){
		return power;
	}
	public int[] getattackrange(){
		return attackrange;
	}
	public skill[] getSkill(){
		return s;
	}
}

